---
# tasks file for podman

- name: "Add {{ ansible_distribution }} repository"
  ansible.builtin.include_tasks: "add_{{ ansible_distribution }}_repos.yml"
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Install libseccomp2 from backports (Debian 10)
  ansible.builtin.apt:
    name: libseccomp2
    state: latest
    default_release: buster-backports
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version | int(0) == 10

- name: Install podman packages
  ansible.builtin.package:
    name: "{{ podman_packages }}"
    state: present
    update_cache: yes

- name: Set user.max_user_namespaces
  ansible.posix.sysctl:
    name: user.max_user_namespaces
    value: "{{ podman_max_user_namespaces | string }}"
    sysctl_set: yes
    state: present
    reload: yes
  when:
    - podman_max_user_namespaces is defined
    - podman_max_user_namespaces is number
